package com.boardbanker.core.model

import kotlinx.serialization.Serializable

@Serializable
enum class TransactionType {
    GAME_START,
    PROPERTY_PURCHASE,
    RENT_PAYMENT,
    BANK_CREDIT,
    BANK_DEBIT,
    PROPERTY_RENT_LEVEL_CHANGE,
    PROPERTY_OWNERSHIP_CHANGE,
    PROPERTY_SWAP,
    COLOR_SET_COMPLETION_BONUS,
    LOCATION_FEE,
    AUCTION_WIN,
    AUCTION_PURCHASE,
    EVENT_APPLIED,
    TEMPORARY_EFFECT_CREATED,
    TEMPORARY_EFFECT_CONSUMED,
    JAIL_STATUS_CHANGE,
    JAIL_PASS_USED,
    TURN_SKIPPED,
    TURN_ADVANCED,
    EXTRA_TURN_GRANTED,
    EXTRA_TURN_STARTED,
    EXTRA_TURN_CANCELLED_BY_SKIP,
    EXTRA_TURN_CANCELLED_BY_JAIL,
    BANKRUPTCY,
    UNDO,
}
