"""Manually verified game data extracted from physical card front images (Step 3).

Source: preferred front assets listed in data/cards.json.
Purchase prices confirmed separately from game board data (not printed on card fronts).
"""

from __future__ import annotations

PROPERTY_MASTER_VALUES: list[dict] = [
    {"id": "PRP_01", "name": "Old Kent Road", "group": "BROWN", "purchasePrice": 60, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [70, 130, 220, 370, 750]},
    {"id": "PRP_02", "name": "Whitechapel Road", "group": "BROWN", "purchasePrice": 60, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [70, 130, 220, 370, 750]},
    {"id": "PRP_03", "name": "The Angel, Islington", "group": "LIGHT_BLUE", "purchasePrice": 100, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [80, 140, 240, 410, 800]},
    {"id": "PRP_04", "name": "Euston Road", "group": "LIGHT_BLUE", "purchasePrice": 100, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [80, 140, 240, 410, 800]},
    {"id": "PRP_05", "name": "Pentonville Road", "group": "LIGHT_BLUE", "purchasePrice": 120, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [100, 160, 260, 440, 860]},
    {"id": "PRP_06", "name": "Pall Mall", "group": "PINK", "purchasePrice": 140, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [110, 180, 290, 460, 900]},
    {"id": "PRP_07", "name": "Whitehall", "group": "PINK", "purchasePrice": 140, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [110, 180, 290, 460, 900]},
    {"id": "PRP_08", "name": "Northumberland Avenue", "group": "PINK", "purchasePrice": 160, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [130, 200, 310, 490, 980]},
    {"id": "PRP_09", "name": "Bow Street", "group": "ORANGE", "purchasePrice": 180, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [140, 210, 330, 520, 1000]},
    {"id": "PRP_10", "name": "Marlborough Street", "group": "ORANGE", "purchasePrice": 180, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [140, 210, 330, 520, 1000]},
    {"id": "PRP_11", "name": "Vine Street", "group": "ORANGE", "purchasePrice": 200, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [160, 230, 350, 550, 1100]},
    {"id": "PRP_12", "name": "Strand", "group": "RED", "purchasePrice": 220, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [170, 250, 380, 580, 1160]},
    {"id": "PRP_13", "name": "Fleet Street", "group": "RED", "purchasePrice": 220, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [170, 250, 380, 580, 1160]},
    {"id": "PRP_14", "name": "Trafalgar Square", "group": "RED", "purchasePrice": 240, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [190, 270, 400, 610, 1200]},
    {"id": "PRP_15", "name": "Leicester Square", "group": "YELLOW", "purchasePrice": 260, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [200, 280, 420, 640, 1300]},
    {"id": "PRP_16", "name": "Coventry Street", "group": "YELLOW", "purchasePrice": 260, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [200, 280, 420, 640, 1300]},
    {"id": "PRP_17", "name": "Piccadilly", "group": "YELLOW", "purchasePrice": 280, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [220, 300, 440, 670, 1340]},
    {"id": "PRP_18", "name": "Regent Street", "group": "GREEN", "purchasePrice": 300, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [230, 320, 460, 700, 1400]},
    {"id": "PRP_19", "name": "Oxford Street", "group": "GREEN", "purchasePrice": 300, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [230, 320, 460, 700, 1400]},
    {"id": "PRP_20", "name": "Bond Street", "group": "GREEN", "purchasePrice": 320, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [250, 340, 480, 730, 1440]},
    {"id": "PRP_21", "name": "Park Lane", "group": "DARK_BLUE", "purchasePrice": 350, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [270, 360, 510, 740, 1500]},
    {"id": "PRP_22", "name": "Mayfair", "group": "DARK_BLUE", "purchasePrice": 400, "initialRentLevel": 1, "maximumRentLevel": 5, "rents": [300, 400, 560, 810, 1600]},
]

PROPERTY_MASTER_BY_ID = {entry["id"]: entry for entry in PROPERTY_MASTER_VALUES}

COLOR_GROUP_LABELS = {
    "BROWN": "Brown",
    "LIGHT_BLUE": "Light Blue",
    "PINK": "Pink",
    "ORANGE": "Orange",
    "RED": "Red",
    "YELLOW": "Yellow",
    "GREEN": "Green",
    "DARK_BLUE": "Dark Blue",
}

PROPERTY_EXTRACTIONS: dict[str, dict] = {
    "PRP_01": {
        "colorGroup": "BROWN",
        "colorGroupLabel": "Brown",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 70},
            {"level": 2, "amount": 130},
            {"level": 3, "amount": 220},
            {"level": 4, "amount": 370},
            {"level": 5, "amount": 750},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "OLD KENT ROAD. RENT LEVEL 1-5. RENT: 70, 130, 220, 370, 750. Sequence: 1. © 1935, 2015 Hasbro.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_02": {
        "colorGroup": "BROWN",
        "colorGroupLabel": "Brown",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 70},
            {"level": 2, "amount": 130},
            {"level": 3, "amount": 220},
            {"level": 4, "amount": 370},
            {"level": 5, "amount": 750},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "WHITECHAPEL ROAD. RENT LEVEL 1-5. RENT: 70, 130, 220, 370, 750. Sequence: 2.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_03": {
        "colorGroup": "LIGHT_BLUE",
        "colorGroupLabel": "Light Blue",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 80},
            {"level": 2, "amount": 140},
            {"level": 3, "amount": 240},
            {"level": 4, "amount": 410},
            {"level": 5, "amount": 800},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "THE ANGEL, ISLINGTON. RENT LEVEL 1-5. RENT: 80, 140, 240, 410, 800. Sequence: 3.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_04": {
        "colorGroup": "LIGHT_BLUE",
        "colorGroupLabel": "Light Blue",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 80},
            {"level": 2, "amount": 140},
            {"level": 3, "amount": 240},
            {"level": 4, "amount": 410},
            {"level": 5, "amount": 800},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "EUSTON ROAD. RENT LEVEL 1-5. RENT: 80, 140, 240, 410, 800. Sequence: 4.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_05": {
        "colorGroup": "LIGHT_BLUE",
        "colorGroupLabel": "Light Blue",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 100},
            {"level": 2, "amount": 160},
            {"level": 3, "amount": 260},
            {"level": 4, "amount": 440},
            {"level": 5, "amount": 860},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "PENTONVILLE ROAD. RENT LEVEL 1-5. RENT: 100, 160, 260, 440, 860. Sequence: 5.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_06": {
        "colorGroup": "PINK",
        "colorGroupLabel": "Pink",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 110},
            {"level": 2, "amount": 180},
            {"level": 3, "amount": 290},
            {"level": 4, "amount": 460},
            {"level": 5, "amount": 900},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "PALL MALL. RENT LEVEL 1-5. RENT: 110, 180, 290, 460, 900. Sequence: 6.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_07": {
        "colorGroup": "PINK",
        "colorGroupLabel": "Pink",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 110},
            {"level": 2, "amount": 180},
            {"level": 3, "amount": 290},
            {"level": 4, "amount": 460},
            {"level": 5, "amount": 900},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "WHITEHALL. RENT LEVEL 1-5. RENT: 110, 180, 290, 460, 900. Sequence: 7.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_08": {
        "colorGroup": "PINK",
        "colorGroupLabel": "Pink",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 130},
            {"level": 2, "amount": 200},
            {"level": 3, "amount": 310},
            {"level": 4, "amount": 490},
            {"level": 5, "amount": 980},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "NORTHUMBERLAND AVENUE. RENT LEVEL 1-5. RENT: 130, 200, 310, 490, 980. Sequence: 8.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_09": {
        "colorGroup": "ORANGE",
        "colorGroupLabel": "Orange",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 140},
            {"level": 2, "amount": 210},
            {"level": 3, "amount": 330},
            {"level": 4, "amount": 520},
            {"level": 5, "amount": 1000},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "BOW STREET. RENT LEVEL 1-5. RENT: 140, 210, 330, 520, 1000. Sequence: 9.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_10": {
        "colorGroup": "ORANGE",
        "colorGroupLabel": "Orange",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 140},
            {"level": 2, "amount": 210},
            {"level": 3, "amount": 330},
            {"level": 4, "amount": 520},
            {"level": 5, "amount": 1000},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "MARLBOROUGH STREET. RENT LEVEL 1-5. RENT: 140, 210, 330, 520, 1000. Sequence: 10.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_11": {
        "colorGroup": "ORANGE",
        "colorGroupLabel": "Orange",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 160},
            {"level": 2, "amount": 230},
            {"level": 3, "amount": 350},
            {"level": 4, "amount": 550},
            {"level": 5, "amount": 1100},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "VINE STREET. RENT LEVEL 1-5. RENT: 160, 230, 350, 550, 1100. Sequence: 11.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_12": {
        "colorGroup": "RED",
        "colorGroupLabel": "Red",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 170},
            {"level": 2, "amount": 250},
            {"level": 3, "amount": 380},
            {"level": 4, "amount": 580},
            {"level": 5, "amount": 1160},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "STRAND. RENT LEVEL 1-5. RENT: 170, 250, 380, 580, 1160. Sequence: 12.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_13": {
        "colorGroup": "RED",
        "colorGroupLabel": "Red",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 170},
            {"level": 2, "amount": 250},
            {"level": 3, "amount": 380},
            {"level": 4, "amount": 580},
            {"level": 5, "amount": 1160},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "FLEET STREET. RENT LEVEL 1-5. RENT: 170, 250, 380, 580, 1160. Sequence: 13.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_14": {
        "colorGroup": "RED",
        "colorGroupLabel": "Red",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 190},
            {"level": 2, "amount": 270},
            {"level": 3, "amount": 400},
            {"level": 4, "amount": 610},
            {"level": 5, "amount": 1200},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "TRAFALGAR SQUARE. RENT LEVEL 1-5. RENT: 190, 270, 400, 610, 1200. Sequence: 14.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_15": {
        "colorGroup": "YELLOW",
        "colorGroupLabel": "Yellow",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 200},
            {"level": 2, "amount": 280},
            {"level": 3, "amount": 420},
            {"level": 4, "amount": 640},
            {"level": 5, "amount": 1300},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "LEICESTER SQUARE. RENT LEVEL 1-5. RENT: 200, 280, 420, 640, 1300. Sequence: 15.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_16": {
        "colorGroup": "YELLOW",
        "colorGroupLabel": "Yellow",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 200},
            {"level": 2, "amount": 280},
            {"level": 3, "amount": 420},
            {"level": 4, "amount": 640},
            {"level": 5, "amount": 1300},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "COVENTRY STREET. RENT LEVEL 1-5. RENT: 200, 280, 420, 640, 1300. Sequence: 16.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_17": {
        "colorGroup": "YELLOW",
        "colorGroupLabel": "Yellow",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 220},
            {"level": 2, "amount": 300},
            {"level": 3, "amount": 440},
            {"level": 4, "amount": 670},
            {"level": 5, "amount": 1340},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "PICCADILLY. RENT LEVEL 1-5. RENT: 220, 300, 440, 670, 1340. Sequence: 17.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_18": {
        "colorGroup": "GREEN",
        "colorGroupLabel": "Green",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 230},
            {"level": 2, "amount": 320},
            {"level": 3, "amount": 460},
            {"level": 4, "amount": 700},
            {"level": 5, "amount": 1400},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "REGENT STREET. RENT LEVEL 1-5. RENT: 230, 320, 460, 700, 1400. Sequence: 18.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_19": {
        "colorGroup": "GREEN",
        "colorGroupLabel": "Green",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 230},
            {"level": 2, "amount": 320},
            {"level": 3, "amount": 460},
            {"level": 4, "amount": 700},
            {"level": 5, "amount": 1400},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "OXFORD STREET. RENT LEVEL 1-5. RENT: 230, 320, 460, 700, 1400. Sequence: 19.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_20": {
        "colorGroup": "GREEN",
        "colorGroupLabel": "Green",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 250},
            {"level": 2, "amount": 340},
            {"level": 3, "amount": 480},
            {"level": 4, "amount": 730},
            {"level": 5, "amount": 1440},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "BOND STREET. RENT LEVEL 1-5. RENT: 250, 340, 480, 730, 1440. Sequence: 20.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_21": {
        "colorGroup": "DARK_BLUE",
        "colorGroupLabel": "Dark Blue",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 270},
            {"level": 2, "amount": 360},
            {"level": 3, "amount": 510},
            {"level": 4, "amount": 740},
            {"level": 5, "amount": 1500},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "PARK LANE. RENT LEVEL 1-5. RENT: 270, 360, 510, 740, 1500. Sequence: 21.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
    "PRP_22": {
        "colorGroup": "DARK_BLUE",
        "colorGroupLabel": "Dark Blue",
        "purchasePrice": None,
        "rentLevels": [
            {"level": 1, "amount": 300},
            {"level": 2, "amount": 400},
            {"level": 3, "amount": 560},
            {"level": 4, "amount": 810},
            {"level": 5, "amount": 1600},
        ],
        "maximumRentLevel": 5,
        "rawVisibleText": "MAYFAIR. RENT LEVEL 1-5. RENT: 300, 400, 560, 810, 1600. Sequence: 22.",
        "extractionStatus": "NEEDS_REVIEW",
        "notes": "Purchase price not printed on card front.",
    },
}

EVENT_MASTER_VALUES: list[dict] = [
    {"id": "EVT_01", "name": "Boom Town", "printedText": "Property prices bounce back! Move to any property space. Tap this card then the property card to buy it, auction it or raise rent level +1."},
    {"id": "EVT_02", "name": "Crime Down", "printedText": "Police arrest local newspaper thief! Tap this card then one of your property cards. (Colour set rent level jumps +1)"},
    {"id": "EVT_03", "name": "Deal Of The Week", "printedText": "Word on the street says the market is booming! Move to any property space. Tap this card then the property card to buy it, auction it or raise rent level +1."},
    {"id": "EVT_04", "name": "Demolished", "printedText": "Your builders get the wrong address! Tap this card then any property card. (Rent level resets to 1)"},
    {"id": "EVT_05", "name": "Grand Designs", "printedText": "One of your properties gets a TV makeover! Tap this card then one of your property cards. (Rent level jumps to 5)"},
    {"id": "EVT_06", "name": "Haunted House", "printedText": "Something strange is going on! Swap another player's property with one of yours. Pick another player. Tap this card then you each tap one of your property cards to swap. Exchange cards too!"},
    {"id": "EVT_07", "name": "Highway Tax", "printedText": "Your roads need repairs! Tap this card then your Bank card to pay M50 per property you own."},
    {"id": "EVT_08", "name": "House Party", "printedText": "The good times go on till late! Tap this card then one of your property cards. (Rent level jumps to +1 for you; drops -1 for your neighbours)"},
    {"id": "EVT_09", "name": "In The Money", "printedText": "Spend your lottery millions! Swap another player's property with one of yours. Pick another player. Tap this card then you each tap one of your property cards to swap. Exchange cards too!"},
    {"id": "EVT_10", "name": "It's A Boy!", "printedText": "Your new arrival wakes up the whole street! Tap this card then one of your property cards. (Rent level jumps to +1 for you; drops -1 for your neighbours)"},
    {"id": "EVT_11", "name": "Love Is In The Air", "printedText": "Meet someone special right up your street! Pick another player. Tap this card then both your Bank cards to collect M200."},
    {"id": "EVT_12", "name": "On The Map", "printedText": "The new railway station gets the go-ahead! Tap this card then one of your property cards. (Colour set rent level jumps +1)"},
    {"id": "EVT_13", "name": "On The Run", "printedText": "The summer marathon shuts down the roads! Tap this card. (Players pay level 1 rent only for the next two rent payments)"},
    {"id": "EVT_14", "name": "Pick Your Own", "printedText": "Catch someone stealing your prize tomatoes! Tap this card and send another player to Jail."},
    {"id": "EVT_15", "name": "Pong! What A Stinker", "printedText": "The local sewer springs a leak! Tap this card then one of your property cards. (Rent level drops -1 for that side of the board)"},
    {"id": "EVT_16", "name": "Rover's Revenge", "printedText": "Your pet pooch poops on someone's patio! Tap this card then any property card. (Rent level resets to 1)"},
    {"id": "EVT_17", "name": "Stargazing", "printedText": "The hottest A-list celebrity moves in next door! Tap this card then one of your property cards. (Colour set rent level jumps +1)"},
    {"id": "EVT_18", "name": "Stop The Presses", "printedText": "Get the lowdown on a hot property! Move to any property space. Tap this card then the property card to buy it, auction it or raise rent level +1."},
    {"id": "EVT_19", "name": "'Tis The Season", "printedText": "You've caught that nasty cough going around! Tap this card then one of your property cards. (Colour set rent level drops -1)"},
    {"id": "EVT_20", "name": "Tornado Alley", "printedText": "Hey, where did the roof go? Tap this card then any property card. (Rent level resets to 1)"},
    {"id": "EVT_21", "name": "Total Gridlock", "printedText": "Faulty traffic lights get the street in a jam! Tap this card and all players move directly to Free Parking. Do not pass GO! If you are in Jail, stay there!"},
    {"id": "EVT_22", "name": "What A Ride!", "printedText": "Your local theme park builds the world's craziest roller-coaster! Tap this card then one of your property cards. (Rent level jumps +1 for that side of the board)"},
    {"id": "EVT_23", "name": "Wibble Wobble", "printedText": "Sit in a bath of jelly with a friend for charity! Pick another player. Tap this card then both your Bank cards to collect M200."},
]

ENGINE_IMPLEMENTATION_NEEDS_REVIEW = {
    "EVT_08",
    "EVT_10",
    "EVT_13",
    "EVT_15",
    "EVT_21",
    "EVT_22",
}

EVENT_MASTER_BY_ID = {entry["id"]: entry for entry in EVENT_MASTER_VALUES}

EVENT_EXTRACTIONS: dict[str, dict] = {
    "EVT_01": {
        "printedText": "Property prices bounce back! Move to any property space. Tap this card then the property card to buy it, auction it or raise rent level +1.",
        "effectClassification": ["MOVE_PLAYER", "SELECT_PROPERTY", "SPECIAL_RULE"],
        "parsedEffect": {
            "action": "MOVE_THEN_PROPERTY_CHOICE",
            "amount": 1,
            "target": "SELECTED_PROPERTY",
            "parameters": {"choices": ["BUY", "AUCTION", "RAISE_RENT_LEVEL"]},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_02": {
        "printedText": "Police arrest local newspaper thief! Tap this card then one of your property cards. (Colour set rent level jumps + 1)",
        "effectClassification": ["PROPERTY_RENT_INCREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "INCREASE_COLOR_SET_RENT_LEVEL",
            "amount": 1,
            "target": "OWNED_PROPERTY",
            "parameters": {"scope": "COLOR_SET"},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_03": {
        "printedText": "Word on the street says the market is booming! Move to any property space. Tap this card then the property card to buy it, auction it or raise rent level +1.",
        "effectClassification": ["MOVE_PLAYER", "SELECT_PROPERTY", "SPECIAL_RULE"],
        "parsedEffect": {
            "action": "MOVE_THEN_PROPERTY_CHOICE",
            "amount": 1,
            "target": "SELECTED_PROPERTY",
            "parameters": {"choices": ["BUY", "AUCTION", "RAISE_RENT_LEVEL"]},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_04": {
        "printedText": "Your builders get the wrong address! Tap this card then any property card. (Rent level resets to 1)",
        "effectClassification": ["PROPERTY_RENT_DECREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "RESET_PROPERTY_RENT_LEVEL",
            "amount": 1,
            "target": "ANY_PROPERTY",
            "parameters": {},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_05": {
        "printedText": "One of your properties gets a TV makeover! Tap this card then one of your property cards. (Rent level jumps to 5)",
        "effectClassification": ["PROPERTY_RENT_INCREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "SET_PROPERTY_RENT_LEVEL",
            "amount": 5,
            "target": "OWNED_PROPERTY",
            "parameters": {},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_06": {
        "printedText": "Something strange is going on! Swap another player's property with one of yours. Pick another player. Tap this card then you each tap one of your property cards to swap. Exchange cards too!",
        "effectClassification": ["SELECT_PLAYER", "SELECT_PROPERTY", "AFFECT_PROPERTY", "SPECIAL_RULE"],
        "parsedEffect": {
            "action": "SWAP_PROPERTIES_BETWEEN_PLAYERS",
            "amount": None,
            "target": "TWO_PLAYERS_AND_PROPERTIES",
            "parameters": {"exchangePhysicalCards": True},
        },
        "requiresPlayerScan": True,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "Requires two property scans (one per player) after player selection.",
    },
    "EVT_07": {
        "printedText": "Your roads need repairs! Tap this card then your Bank card to pay M50 per property you own.",
        "effectClassification": ["MONEY_LOSS", "SELECT_PLAYER"],
        "parsedEffect": {
            "action": "PAY_PER_OWNED_PROPERTY",
            "amount": 50,
            "target": "CURRENT_PLAYER",
            "parameters": {"perProperty": True},
        },
        "requiresPlayerScan": True,
        "requiresPropertyScan": False,
        "extractionStatus": "COMPLETE",
        "notes": "Card uses Monopoly currency symbol before 50.",
    },
    "EVT_08": {
        "printedText": "The good times go on till late! Tap this card then one of your property cards. (Rent level jumps to +1 for you; drops -1 for your neighbours)",
        "effectClassification": ["PROPERTY_RENT_INCREASE", "PROPERTY_RENT_DECREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "TO_BE_CONFIRMED",
            "amount": 1,
            "target": "OWNED_PROPERTY_AND_NEIGHBOURS",
            "parameters": {"selectedPropertyRentChange": 1, "neighbourRentChange": -1},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "NEEDS_REVIEW",
        "printedRuleStatus": "RESOLVED",
        "engineImplementationStatus": "NEEDS_REVIEW",
        "notes": "Printed rule confirmed. Engine semantics for 'neighbours' not yet defined.",
    },
    "EVT_09": {
        "printedText": "Spend your lottery millions! Swap another player's property with one of yours. Pick another player. Tap this card then you each tap one of your property cards to swap. Exchange cards too!",
        "effectClassification": ["SELECT_PLAYER", "SELECT_PROPERTY", "AFFECT_PROPERTY", "SPECIAL_RULE"],
        "parsedEffect": {
            "action": "SWAP_PROPERTIES_BETWEEN_PLAYERS",
            "amount": None,
            "target": "TWO_PLAYERS_AND_PROPERTIES",
            "parameters": {"exchangePhysicalCards": True},
        },
        "requiresPlayerScan": True,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "Requires two property scans (one per player) after player selection.",
    },
    "EVT_10": {
        "printedText": "Your new arrival wakes up the whole street! Tap this card then one of your property cards. (Rent level jumps to +1 for you; drops -1 for your neighbours)",
        "effectClassification": ["PROPERTY_RENT_INCREASE", "PROPERTY_RENT_DECREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "TO_BE_CONFIRMED",
            "amount": 1,
            "target": "OWNED_PROPERTY_AND_NEIGHBOURS",
            "parameters": {"selectedPropertyRentChange": 1, "neighbourRentChange": -1},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "NEEDS_REVIEW",
        "printedRuleStatus": "RESOLVED",
        "engineImplementationStatus": "NEEDS_REVIEW",
        "notes": "Printed rule confirmed. Engine semantics for 'neighbours' not yet defined.",
    },
    "EVT_11": {
        "printedText": "Meet someone special right up your street! Pick another player. Tap this card then both your Bank cards to collect M200.",
        "effectClassification": ["MONEY_GAIN", "SELECT_PLAYER", "AFFECT_ALL_PLAYERS"],
        "parsedEffect": {
            "action": "CREDIT_BOTH_PLAYERS",
            "amount": 200,
            "target": "CURRENT_PLAYER_AND_CHOSEN_PLAYER",
            "parameters": {},
        },
        "requiresPlayerScan": True,
        "requiresPropertyScan": False,
        "extractionStatus": "COMPLETE",
        "notes": "Both players receive 200. Requires two player card scans.",
    },
    "EVT_12": {
        "printedText": "The new railway station gets the go-ahead! Tap this card then one of your property cards. (Colour set rent level jumps +1)",
        "effectClassification": ["PROPERTY_RENT_INCREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "INCREASE_COLOR_SET_RENT_LEVEL",
            "amount": 1,
            "target": "OWNED_PROPERTY",
            "parameters": {"scope": "COLOR_SET"},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_13": {
        "printedText": "The summer marathon shuts down the roads! Tap this card. (Players pay level 1 rent only for the next two rent payments)",
        "effectClassification": ["SPECIAL_RULE", "AFFECT_ALL_PLAYERS"],
        "parsedEffect": {
            "action": "TEMPORARY_RENT_CAP",
            "amount": 1,
            "target": "ALL_PLAYERS",
            "parameters": {"durationRentPayments": 2, "maxRentLevel": 1},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": False,
        "extractionStatus": "NEEDS_REVIEW",
        "printedRuleStatus": "RESOLVED",
        "engineImplementationStatus": "NEEDS_REVIEW",
        "notes": "Printed rule confirmed. Engine tracking for 'next two rent payments' not yet defined.",
    },
    "EVT_14": {
        "printedText": "Catch someone stealing your prize tomatoes! Tap this card and send another player to Jail.",
        "effectClassification": ["GO_TO_JAIL", "SELECT_PLAYER"],
        "parsedEffect": {
            "action": "SEND_PLAYER_TO_JAIL",
            "amount": None,
            "target": "OTHER_PLAYER",
            "parameters": {},
        },
        "requiresPlayerScan": True,
        "requiresPropertyScan": False,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_15": {
        "printedText": "The local sewer springs a leak! Tap this card then one of your property cards. (Rent level drops -1 for that side of the board)",
        "effectClassification": ["PROPERTY_RENT_DECREASE", "SELECT_PROPERTY", "AFFECT_MULTIPLE_PROPERTIES"],
        "parsedEffect": {
            "action": "TO_BE_CONFIRMED",
            "amount": -1,
            "target": "BOARD_SIDE",
            "parameters": {"determinedByScannedProperty": True},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "NEEDS_REVIEW",
        "printedRuleStatus": "RESOLVED",
        "engineImplementationStatus": "NEEDS_REVIEW",
        "notes": "Printed rule confirmed. Engine semantics for 'that side of the board' not yet defined.",
    },
    "EVT_16": {
        "printedText": "Your pet pooch poops on someone's patio! Tap this card then any property card. (Rent level resets to 1)",
        "effectClassification": ["PROPERTY_RENT_DECREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "RESET_PROPERTY_RENT_LEVEL",
            "amount": 1,
            "target": "ANY_PROPERTY",
            "parameters": {},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_17": {
        "printedText": "The hottest A-list celebrity moves in next door! Tap this card then one of your property cards. (Colour set rent level jumps +1)",
        "effectClassification": ["PROPERTY_RENT_INCREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "INCREASE_COLOR_SET_RENT_LEVEL",
            "amount": 1,
            "target": "OWNED_PROPERTY",
            "parameters": {"scope": "COLOR_SET"},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_18": {
        "printedText": "Get the lowdown on a hot property! Move to any property space. Tap this card then the property card to buy it, auction it or raise rent level +1.",
        "effectClassification": ["MOVE_PLAYER", "SELECT_PROPERTY", "SPECIAL_RULE"],
        "parsedEffect": {
            "action": "MOVE_THEN_PROPERTY_CHOICE",
            "amount": 1,
            "target": "SELECTED_PROPERTY",
            "parameters": {"choices": ["BUY", "AUCTION", "RAISE_RENT_LEVEL"]},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_19": {
        "printedText": "You've caught that nasty cough going around! Tap this card then one of your property cards. (Colour set rent level drops -1)",
        "effectClassification": ["PROPERTY_RENT_DECREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "DECREASE_COLOR_SET_RENT_LEVEL",
            "amount": 1,
            "target": "OWNED_PROPERTY",
            "parameters": {"scope": "COLOR_SET"},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_20": {
        "printedText": "Hey, where did the roof go? Tap this card then any property card. (Rent level resets to 1)",
        "effectClassification": ["PROPERTY_RENT_DECREASE", "SELECT_PROPERTY", "AFFECT_PROPERTY"],
        "parsedEffect": {
            "action": "RESET_PROPERTY_RENT_LEVEL",
            "amount": 1,
            "target": "ANY_PROPERTY",
            "parameters": {},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "COMPLETE",
        "notes": "",
    },
    "EVT_21": {
        "printedText": "Faulty traffic lights get the street in a jam! Tap this card and all players move directly to Free Parking. Do not pass GO! If you are in Jail, stay there!",
        "effectClassification": ["MOVE_PLAYER", "AFFECT_ALL_PLAYERS", "SPECIAL_RULE"],
        "parsedEffect": {
            "action": "MOVE_ALL_TO_FREE_PARKING",
            "amount": None,
            "target": "ALL_PLAYERS",
            "parameters": {"passGo": False, "jailPlayersRemain": True},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": False,
        "extractionStatus": "NEEDS_REVIEW",
        "printedRuleStatus": "RESOLVED",
        "engineImplementationStatus": "NEEDS_REVIEW",
        "notes": (
            "Printed rule confirmed. Version 1: physical board/tokens remain authoritative for "
            "position; app displays instruction, blocks GO payment, preserves Jail state, and "
            "players manually move eligible tokens to Free Parking. No digital board movement."
        ),
    },
    "EVT_22": {
        "printedText": "Your local theme park builds the world's craziest roller-coaster! Tap this card then one of your property cards. (Rent level jumps +1 for that side of the board)",
        "effectClassification": ["PROPERTY_RENT_INCREASE", "SELECT_PROPERTY", "AFFECT_MULTIPLE_PROPERTIES"],
        "parsedEffect": {
            "action": "TO_BE_CONFIRMED",
            "amount": 1,
            "target": "BOARD_SIDE",
            "parameters": {"determinedByScannedProperty": True},
        },
        "requiresPlayerScan": False,
        "requiresPropertyScan": True,
        "extractionStatus": "NEEDS_REVIEW",
        "printedRuleStatus": "RESOLVED",
        "engineImplementationStatus": "NEEDS_REVIEW",
        "notes": "Printed rule confirmed. Engine semantics for 'that side of the board' not yet defined.",
    },
    "EVT_23": {
        "printedText": "Sit in a bath of jelly with a friend for charity! Pick another player. Tap this card then both your Bank cards to collect M200.",
        "effectClassification": ["MONEY_GAIN", "SELECT_PLAYER", "AFFECT_ALL_PLAYERS"],
        "parsedEffect": {
            "action": "CREDIT_BOTH_PLAYERS",
            "amount": 200,
            "target": "CURRENT_PLAYER_AND_CHOSEN_PLAYER",
            "parameters": {},
        },
        "requiresPlayerScan": True,
        "requiresPropertyScan": False,
        "extractionStatus": "COMPLETE",
        "notes": "Both players receive 200. Requires two player card scans.",
    },
}

for _property_id, _master in PROPERTY_MASTER_BY_ID.items():
    if _property_id not in PROPERTY_EXTRACTIONS:
        continue
    extraction = PROPERTY_EXTRACTIONS[_property_id]
    extraction["displayName"] = _master["name"]
    extraction["colorGroup"] = _master["group"]
    extraction["colorGroupLabel"] = COLOR_GROUP_LABELS[_master["group"]]
    extraction["purchasePrice"] = _master["purchasePrice"]
    extraction["initialRentLevel"] = _master["initialRentLevel"]
    extraction["maximumRentLevel"] = _master["maximumRentLevel"]
    extraction["rentLevels"] = [
        {"level": index, "amount": amount}
        for index, amount in enumerate(_master["rents"], start=1)
    ]
    extraction["extractionStatus"] = "COMPLETE"
    extraction["notes"] = "Master values confirmed from provided game data."

for _event_id, _master in EVENT_MASTER_BY_ID.items():
    if _event_id not in EVENT_EXTRACTIONS:
        continue
    extraction = EVENT_EXTRACTIONS[_event_id]
    extraction["displayName"] = _master["name"]
    extraction["eventSubtitle"] = _master.get("eventSubtitle", "")
    extraction["eventDescription"] = _master.get(
        "eventDescription",
        _master.get("printedText", ""),
    )
    extraction["printedTextValidated"] = True
    extraction["printedRuleStatus"] = "RESOLVED"
    if _event_id in ENGINE_IMPLEMENTATION_NEEDS_REVIEW:
        extraction["engineImplementationStatus"] = "NEEDS_REVIEW"
        extraction["extractionStatus"] = "NEEDS_REVIEW"
    else:
        extraction["engineImplementationStatus"] = "COMPLETE"
        extraction["extractionStatus"] = "COMPLETE"
        extraction.setdefault("printedRuleStatus", "RESOLVED")
